;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        easy-kill
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        helm-confirm-and-exit-minibuffer
        helm-show-kill-ring
        indent-for-tab-command
        kmacro-end-and-call-macro
        org-beginning-of-line
        org-delete-char
        org-self-insert-command
        org-shiftdown
        ))

(setq mc/cmds-to-run-once
      '(
        avy-goto-char
        crux-kill-line-backwards
        helm-M-x
        helm-projectile-ag
        kill-region
        mouse-set-region
        org-end-of-line
        previous-buffer
        suspend-frame
        swiper
        yaml-electric-backspace
        ))
